<?xml version="1.0" encoding="utf-8"?>
<search>
  
    
    <entry>
      <title><![CDATA[ansible的setup模块可能导致进程卡死]]></title>
      <url>%2F2017%2F01%2F07%2Fansible-setup-module-problem-md%2F</url>
      <content type="text"><![CDATA[问题背景 概述 一次 playbook 的测试过程中，发现一个奇怪的现象：就是执行 playbook 的过程中，总会出现一个 setup 的步骤，并且这个步骤执行的时间非常的长，达到5分钟，甚至有的环境会直接卡死，进程无法中断。详细的问题描述见github-ansible 环境介绍 通过ansible节点管理openstack环境,所以环境中有很多虚拟网卡，导致setup模块的问题。 问题现象 test.yaml 文件 12345---- hosts: xx.xx.xx.xx tasks: - name: test shell: echo aaaa 执行之后，直接卡死，就像下面这样，一直没有返回。 12345# ansible-playbook test.yamlPLAY [xx.xx.xx.xx] ************************************************************TASK [setup] ******************************************************************* 问题分析分别到ansible节点和目标节点查看原因。 ansible节点 1237901 pts/2 Sl+ 2:43 \_ /usr/bin/python /usr/bin/ansible all -m setup7912 pts/2 S+ 0:00 \_ /usr/bin/python /usr/bin/ansible all -m setup7960 pts/2 S+ 0:00 \_ ssh -C -o ControlMaster=auto -o ControlPersist=60s -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r -tt xx.xx.xx.xx /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1483608708.39-143999004080315/setup.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1483608708.39-143999004080315/" &gt; /dev/null 2&gt;&amp;1 &amp;&amp; sleep 0' 目标节点 12349036 pts/1 Ss+ 0:00 /bin/sh -c /usr/bin/python /root/.ansible/tmp/ansible-tmp-1483608708.39-143999004080315/setup.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1483608708.39-143999004080315/" &gt; /dev/null 2&gt;&amp;1 &amp;&amp; sleep 0 49083 pts/1 S+ 0:00 \_ /usr/bin/python /root/.ansible/tmp/ansible-tmp-1483608708.39-143999004080315/setup.py 49213 pts/1 D+ 0:00 \_ /usr/bin/python /tmp/ansible_bx9h6K/ansible_module_setup.py 请注意，这里进程进入了 D 状态，这个状态的意思是不可中断的进程，会一直卡着，无法返回。 setup模块 既然问题出在 setup 模块，那就先来看下setup 模块是干什么的，通过查看源码和文档，这个是获取系统信息，并将相关变量存储到facts中，具体的就不在这里展开分析了。 其中获取网卡信息，过程大概如下123456789101180013 pts/2 Ss+ 0:00 /bin/sh -c /usr/bin/python /root/.ansible/tmp/ansible-tmp-1483615192.93-195988658363074/setup.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1483615192.93-195988658363074/" &gt; /dev/null 2&gt;&amp;1 &amp;&amp; sleep 0 80034 pts/2 S+ 0:00 \_ /usr/bin/python /root/.ansible/tmp/ansible-tmp-1483615192.93-195988658363074/setup.py 80073 pts/2 S+ 0:00 \_ /usr/bin/python /tmp/ansible_pBITNP/ansible_module_setup.py 80092 pts/2 Sl+ 0:25 \_ /usr/bin/ruby /usr/bin/facter --puppet --json 15676 pts/2 R+ 0:00 \_ /sbin/ip link show ovs-system 80013 pts/2 Ss+ 0:00 /bin/sh -c /usr/bin/python /root/.ansible/tmp/ansible-tmp-1483615192.93-195988658363074/setup.py; rm -rf "/root/.ansible/tmp/ansible-tmp-1483615192.93-195988658363074/" &gt; /dev/null 2&gt;&amp;1 &amp;&amp; sleep 0 80034 pts/2 S+ 0:00 \_ /usr/bin/python /root/.ansible/tmp/ansible-tmp-1483615192.93-195988658363074/setup.py 80073 pts/2 S+ 0:00 \_ /usr/bin/python /tmp/ansible_pBITNP/ansible_module_setup.py 80092 pts/2 Sl+ 0:25 \_ /usr/bin/ruby /usr/bin/facter --puppet --json 12971 pts/2 R+ 0:00 \_ /sbin/ip link show ifb992 问题处理openstack的网络节点，会有非常多的虚拟网卡，我的这个环境中虚拟网卡个数接近1000个了，导致收集信息的时间长。既然只是获取信息，那就能否跳过这一个步骤呢？当然是有的，修改配置文件 /etc/ansible/ansible.cfg，其中有一个配置项 gather_subset 1234#原值：#gather_subset=all#新值：gather_subset=!all 修改之后，再次执行playbook，问题得到解决。具体其他的配置项，可以查看setup的源码。]]></content>
    </entry>

    
    <entry>
      <title></title>
      <url>%2F2016%2F12%2F27%2F%E8%AE%B0%E4%B8%80%E6%AC%A1neutron-server%E5%90%AF%E5%8A%A8%E5%A4%B1%E8%B4%A5%2F</url>
      <content type="text"><![CDATA[记一次neutron-server启动失败–lbaas驱动加载失败 问题现象 neutron-server 启动失败，查看日志，发现是加载 lbaas 驱动失败。1234567891011121314151617181920212223242526272829303132333435363738394041424344454647484950515253545556575859606162636465666768697071727374752016-12-27 09:17:17.171 76972 CRITICAL neutron [req-b95ec348-cf8f-4381-83d0-e1447825b2aa ] AttributeError: &apos;NoneType&apos; object has no attribute &apos;provider_name&apos;2016-12-27 09:17:17.171 76972 TRACE neutron Traceback (most recent call last):2016-12-27 09:17:17.171 76972 TRACE neutron File &quot;/usr/bin/neutron-server&quot;, line 10, in &lt;module&gt;2016-12-27 09:17:17.171 76972 TRACE neutron sys.exit(main())2016-12-27 09:17:17.171 76972 TRACE neutron File &quot;/usr/lib/python2.7/site-packages/neutron/cmd/eventlet/server/__init__.py&quot;, line 17, in main2016-12-27 09:17:17.171 76972 TRACE neutron server.main()2016-12-27 09:17:17.171 76972 TRACE neutron File &quot;/usr/lib/python2.7/site-packages/neutron/server/__init__.py&quot;, line 43, in main2016-12-27 09:17:17.171 76972 TRACE neutron neutron_api = service.serve_wsgi(service.NeutronApiService)2016-12-27 09:17:17.171 76972 TRACE neutron File &quot;/usr/lib/python2.7/site-packages/neutron/service.py&quot;, line 106, in serve_wsgi2016-12-27 09:17:17.171 76972 TRACE neutron LOG.exception(_LE(&apos;Unrecoverable error: please check log &apos;2016-12-27 09:17:17.171 76972 TRACE neutron File &quot;/usr/lib/python2.7/site-packages/oslo_utils/excutils.py&quot;, line 85, in __exit__2016-12-27 09:17:17.171 76972 TRACE neutron six.reraise(self.type_, self.value, self.tb)2016-12-27 09:17:17.171 76972 TRACE neutron File &quot;/usr/lib/python2.7/site-packages/neutron/service.py&quot;, line 103, in serve_wsgi2016-12-27 09:17:17.171 76972 TRACE neutron service.start()2016-12-27 09:17:17.171 76972 TRACE neutron File &quot;/usr/lib/python2.7/site-packages/neutron/service.py&quot;, line 74, in start2016-12-27 09:17:17.171 76972 TRACE neutron self.wsgi_app = _run_wsgi(self.app_name)2016-12-27 09:17:17.171 76972 TRACE neutron File &quot;/usr/lib/python2.7/site-packages/neutron/service.py&quot;, line 169, in _run_wsgi2016-12-27 09:17:17.171 76972 TRACE neutron app = config.load_paste_app(app_name)2016-12-27 09:17:17.171 76972 TRACE neutron File &quot;/usr/lib/python2.7/site-packages/neutron/common/config.py&quot;, line 229, in load_paste_app2016-12-27 09:17:17.171 76972 TRACE neutron app = deploy.loadapp(&quot;config:%s&quot; % config_path, name=app_name)2016-12-27 09:17:17.171 76972 TRACE neutron File &quot;/usr/lib/python2.7/site-packages/paste/deploy/loadwsgi.py&quot;, line 247, in loadapp2016-12-27 09:17:17.171 76972 TRACE neutron return loadobj(APP, uri, name=name, **kw)2016-12-27 09:17:17.171 76972 TRACE neutron File &quot;/usr/lib/python2.7/site-packages/paste/deploy/loadwsgi.py&quot;, line 272, in loadobj2016-12-27 09:17:17.171 76972 TRACE neutron return context.create()2016-12-27 09:17:17.171 76972 TRACE neutron File &quot;/usr/lib/python2.7/site-packages/paste/deploy/loadwsgi.py&quot;, line 710, in create2016-12-27 09:17:17.171 76972 TRACE neutron return self.object_type.invoke(self)2016-12-27 09:17:17.171 76972 TRACE neutron File &quot;/usr/lib/python2.7/site-packages/paste/deploy/loadwsgi.py&quot;, line 144, in invoke2016-12-27 09:17:17.171 76972 TRACE neutron **context.local_conf)2016-12-27 09:17:17.171 76972 TRACE neutron File &quot;/usr/lib/python2.7/site-packages/paste/deploy/util.py&quot;, line 56, in fix_call2016-12-27 09:17:17.171 76972 TRACE neutron val = callable(*args, **kw)2016-12-27 09:17:17.171 76972 TRACE neutron File &quot;/usr/lib/python2.7/site-packages/paste/urlmap.py&quot;, line 25, in urlmap_factory2016-12-27 09:17:17.171 76972 TRACE neutron app = loader.get_app(app_name, global_conf=global_conf)2016-12-27 09:17:17.171 76972 TRACE neutron File &quot;/usr/lib/python2.7/site-packages/paste/deploy/loadwsgi.py&quot;, line 350, in get_app2016-12-27 09:17:17.171 76972 TRACE neutron name=name, global_conf=global_conf).create()2016-12-27 09:17:17.171 76972 TRACE neutron File &quot;/usr/lib/python2.7/site-packages/paste/deploy/loadwsgi.py&quot;, line 710, in create2016-12-27 09:17:17.171 76972 TRACE neutron return self.object_type.invoke(self)2016-12-27 09:17:17.171 76972 TRACE neutron File &quot;/usr/lib/python2.7/site-packages/paste/deploy/loadwsgi.py&quot;, line 144, in invoke2016-12-27 09:17:17.171 76972 TRACE neutron **context.local_conf)2016-12-27 09:17:17.171 76972 TRACE neutron File &quot;/usr/lib/python2.7/site-packages/paste/deploy/util.py&quot;, line 56, in fix_call2016-12-27 09:17:17.171 76972 TRACE neutron val = callable(*args, **kw)2016-12-27 09:17:17.171 76972 TRACE neutron File &quot;/usr/lib/python2.7/site-packages/neutron/auth.py&quot;, line 74, in pipeline_factory2016-12-27 09:17:17.171 76972 TRACE neutron app = loader.get_app(pipeline[-1])2016-12-27 09:17:17.171 76972 TRACE neutron File &quot;/usr/lib/python2.7/site-packages/paste/deploy/loadwsgi.py&quot;, line 350, in get_app2016-12-27 09:17:17.171 76972 TRACE neutron name=name, global_conf=global_conf).create()2016-12-27 09:17:17.171 76972 TRACE neutron File &quot;/usr/lib/python2.7/site-packages/paste/deploy/loadwsgi.py&quot;, line 710, in create2016-12-27 09:17:17.171 76972 TRACE neutron return self.object_type.invoke(self)2016-12-27 09:17:17.171 76972 TRACE neutron File &quot;/usr/lib/python2.7/site-packages/paste/deploy/loadwsgi.py&quot;, line 146, in invoke2016-12-27 09:17:17.171 76972 TRACE neutron return fix_call(context.object, context.global_conf, **context.local_conf)2016-12-27 09:17:17.171 76972 TRACE neutron File &quot;/usr/lib/python2.7/site-packages/paste/deploy/util.py&quot;, line 56, in fix_call2016-12-27 09:17:17.171 76972 TRACE neutron val = callable(*args, **kw)2016-12-27 09:17:17.171 76972 TRACE neutron File &quot;/usr/lib/python2.7/site-packages/neutron/api/v2/router.py&quot;, line 71, in factory2016-12-27 09:17:17.171 76972 TRACE neutron return cls(**local_config)2016-12-27 09:17:17.171 76972 TRACE neutron File &quot;/usr/lib/python2.7/site-packages/neutron/api/v2/router.py&quot;, line 75, in __init__2016-12-27 09:17:17.171 76972 TRACE neutron plugin = manager.NeutronManager.get_plugin()2016-12-27 09:17:17.171 76972 TRACE neutron File &quot;/usr/lib/python2.7/site-packages/neutron/manager.py&quot;, line 245, in get_plugin2016-12-27 09:17:17.171 76972 TRACE neutron return weakref.proxy(cls.get_instance().plugin)2016-12-27 09:17:17.171 76972 TRACE neutron File &quot;/usr/lib/python2.7/site-packages/neutron/manager.py&quot;, line 239, in get_instance2016-12-27 09:17:17.171 76972 TRACE neutron cls._create_instance()2016-12-27 09:17:17.171 76972 TRACE neutron File &quot;/usr/lib/python2.7/site-packages/oslo_concurrency/lockutils.py&quot;, line 445, in inner2016-12-27 09:17:17.171 76972 TRACE neutron return f(*args, **kwargs)2016-12-27 09:17:17.171 76972 TRACE neutron File &quot;/usr/lib/python2.7/site-packages/neutron/manager.py&quot;, line 225, in _create_instance2016-12-27 09:17:17.171 76972 TRACE neutron cls._instance = cls()2016-12-27 09:17:17.171 76972 TRACE neutron File &quot;/usr/lib/python2.7/site-packages/neutron/manager.py&quot;, line 129, in __init__2016-12-27 09:17:17.171 76972 TRACE neutron self._load_service_plugins()2016-12-27 09:17:17.171 76972 TRACE neutron File &quot;/usr/lib/python2.7/site-packages/neutron/manager.py&quot;, line 198, in _load_service_plugins2016-12-27 09:17:17.171 76972 TRACE neutron provider)2016-12-27 09:17:17.171 76972 TRACE neutron File &quot;/usr/lib/python2.7/site-packages/neutron/manager.py&quot;, line 166, in _get_plugin_instance2016-12-27 09:17:17.171 76972 TRACE neutron return plugin_class()2016-12-27 09:17:17.171 76972 TRACE neutron File &quot;/usr/lib/python2.7/site-packages/neutron_lbaas/services/loadbalancer/plugin.py&quot;, line 389, in __init__2016-12-27 09:17:17.171 76972 TRACE neutron self._load_drivers()2016-12-27 09:17:17.171 76972 TRACE neutron File &quot;/usr/lib/python2.7/site-packages/neutron_lbaas/services/loadbalancer/plugin.py&quot;, line 405, in _load_drivers2016-12-27 09:17:17.171 76972 TRACE neutron self._check_orphan_loadbalancer_associations(ctx, self.drivers.keys())2016-12-27 09:17:17.171 76972 TRACE neutron File &quot;/usr/lib/python2.7/site-packages/neutron_lbaas/services/loadbalancer/plugin.py&quot;, line 418, in _check_orphan_loadbalancer_associations2016-12-27 09:17:17.171 76972 TRACE neutron if lb.provider.provider_name not in provider_names])2016-12-27 09:17:17.171 76972 TRACE neutron AttributeError: &apos;NoneType&apos; object has no attribute &apos;provider_name&apos; 定位分析 查找lbaas配置文见中 驱动配置部分 1service_provider = LOADBALANCERV2:Haproxy:neutron_lbaas.drivers.haproxy.plugin_driver.HaproxyOnHostPluginDriver:default 查看lb驱动代码文件 路径 /usr/lib/python2.7/site-packages/neutron_lbaas/drivers/haproxy/plugin_driver.py 对比文件路径以及代码与配置文件中值的区别，没有什么问题 开发查找代码原因 发现 lb 启动的时候，会检查现所有 lb 资源的状态，在停止服务时，有一个lb状态为创建中 重启 neutron-server 会报错，需要清理异常状态的lb。 这个问题不仅仅是创建的LB资源，删除时也会存在同样的问题。 代码文件 /usr/lib/python2.7/site-packages/neutron_lbaas/services/loadbalancer/plugin.py 405行 1234567891011121314def _load_drivers(self): &quot;&quot;&quot;Loads plugin-drivers specified in configuration.&quot;&quot;&quot; self.drivers, self.default_provider = service_base.load_drivers( constants.LOADBALANCERV2, self) # NOTE(blogan): this method MUST be called after # service_base.load_drivers to correctly verify verify_lbaas_mutual_exclusion() # we&apos;re at the point when extensions are not loaded yet # so prevent policy from being loaded ctx = ncontext.get_admin_context(load_admin_roles=False) # stop service in case provider was removed, but resources were not self._check_orphan_loadbalancer_associations(ctx, self.drivers.keys()) 问题解决 删除异常状态的lbaas资源 命令列表 123456lbaas-loadbalancer-create LBaaS v2 Create a loadbalancer.lbaas-loadbalancer-delete LBaaS v2 Delete a given loadbalancer.lbaas-loadbalancer-list LBaaS v2 List loadbalancers that belong to a given tenant.lbaas-loadbalancer-list-on-agent List the loadbalancers on a loadbalancer v2 agent.lbaas-loadbalancer-show LBaaS v2 Show information of a given loadbalancer.lbaas-loadbalancer-update LBaaS v2 Update a given loadbalancer. 问题优化 根本原因还是在于没有解耦，创建 lbaas 资源异常只是影响一个或部分用户， 不应该导致整个 `neutron-server` 服务无法启动。 代码优化的建议： 是否考虑启动服务的时候，不去检查异常的资源状态？ 如果一定需要检查，是否能输出更明确的日志？因为运维看到这个日志，不知道是资源异常引起的。 扩展阅读 Lbass 资源创建后会生成一个Haproxy provider drivers 与资源一一对应。当资源创建或者删除时，可能出现一些意外情况，导致这种对应关系没有建立，服务重启时，加载驱动时被检查到了，就异常退出了。 OpenStack Neutron 之 Load Balance 官网Load Balancer as a Service (LBaaS)]]></content>
    </entry>

    
    <entry>
      <title><![CDATA[2016年终讲]]></title>
      <url>%2F2016%2F12%2F23%2F2016%E5%B9%B4%E7%BB%88%E8%AE%B2%2F</url>
      <content type="text"><![CDATA[2016年终讲时间过的很快，不经意间又过了一年。雁过留痕，总要留下点什么。 期望结果 有房子，有车子，说走就走的旅行； 云计算，做平台，踏踏实实的创业； 实际现象 科技园，忙创业，路漫长； 代码汪，黑锅侠，躺中枪； 遭收购，汪侠包，销售慌； 人心去，无鼎力，途茫茫；]]></content>
    </entry>

    
    <entry>
      <title></title>
      <url>%2F2016%2F12%2F21%2Fatom.windows%2F</url>
      <content type="text"><![CDATA[https://github.com/atom/atom/blob/master/docs/build-instructions/windows.md]]></content>
    </entry>

    
    <entry>
      <title><![CDATA[helloblog]]></title>
      <url>%2F2016%2F12%2F07%2Fhelloblog%2F</url>
      <content type="text"><![CDATA[博客终于开张了！一直想整一个自己的技术博客，最近终于抽出时间整起来了，感谢gitbub,hexo等相关技术贡献者，给大家带来的免费福利，搭建博客的过程很简单。 为什么要搭建自己的博客？ 为了更好的记录和分享 结交更多志同道合的朋友 表达自己最真实的想法 坚持写作，表达，能更好的理解相关内容 虽然以前也有在 CSDN博客 上写过几篇，但是没有坚持下来（当然也有其他的一些原因），这次打算坚持写下去。以前文笔不好，也许写者写着就好起来了呢；以前不喜欢记录和分享，主要还是太懒了，好记性不如烂笔头，自己写出来的东西才是自己理解的，没有明白这个道理，始终只能在入门阶段徘徊，想要成为一代宗师，自己的总结和思考必不可少。 这并不仅仅只是一个技术博客，也许偶尔也会发发牢骚。 好了，写的有点乱，后面坚持写自己的博客！ 最后，以前的 CSDN博客 不再更新，相关文章也会在近期转移到本博客。]]></content>
    </entry>

    
  
  
</search>
